[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sacsv"
version = "1.5.2"
description = "Swiss Army csv: command-line tools to manipulate csv-formatted data"
authors = [
    { name = "Gabor Nyeki", email = "gabor.nyeki@alumni.duke.edu" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.3.1",
]

[project.scripts]
csv2jsonl = "sacsv.csv2jsonl:cli"
csvaddrandom = "sacsv.csvaddrandom:cli"
csvadduniqueid = "sacsv.csvadduniqueid:cli"
csvaggregate = "sacsv.csvaggregate:cli"
csvappend = "sacsv.csvappend:cli"
csvdropdups = "sacsv.csvdropdups:cli"
csvfindsortkey = "sacsv.csvfindsortkey:cli"
csvkeepmax = "sacsv.csvkeepmax:cli"
csvleftjoin = "sacsv.csvleftjoin:cli"
csvop = "sacsv.csvop:cli"
csvparallel = "sacsv.csvparallel:cli"
csvrename = "sacsv.csvrename:cli"
csvreorder = "sacsv.csvreorder:cli"
csvsed = "sacsv.csvsed:cli"
csvsort = "sacsv.csvsort:cli"
csvtranspose = "sacsv.csvtranspose:cli"
fw2csv = "sacsv.fw2csv:cli"
longcsv2wide = "sacsv.longcsv2wide:cli"
widecsv2long = "sacsv.widecsv2long:cli"

[project.urls]
Homepage = "https://github.com/gn0/sacsv"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101"]
