name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # @v6

      - name: Install uv
        uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # @v7.2.0
        with:
          # Enable caching for faster runs
          enable-cache: true
          cache-suffix: ${{ matrix.python-version }}
          # (Optional) Pin a specific uv version
          version: "latest"

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-extras --dev

      # - name: Run Linting (Ruff)
      #   run: uv run ruff check .

      - name: Run tests
        run: uv run pytest -vv
